"""
ach new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  1 and 2.
By considering the terms in the Fibonacci sequence whose values do not exceed N , find the sum of the even-valued terms.
"""
t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    
    a, b = 1, 2
    res = 0
    while b < n:
        if b % 2 == 0:
            res += b
        a, b = b, a + b
    print(res)
